name: back
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: build
    runs-on: [self-hosted]
    steps:
      - name: Install dependencies
        run: 
          dotnet restore --disable-parallel
      - name: Build
        run: 
          dotnet build --configuration Release --no-restore
  deploy:
    needs: build
    name: deploy
    runs-on: [self-hosted]
    steps:
      - name: Publish artifacts
        run: |
          systemctl stop IpChecker
          dotnet publish -c Release -o /var/www/ip-checker
      - name: Restart bot
        run: |
          systemctl start IpChecker
